console.log("My Name is Manan! Hello World");
let result:boolean =true;
let myData:any=23;
let roll:number=25;
console.log(result+" "+myData+" "+roll);
let firstName:string="Manan";
let lastName:string="Pandya";
console.log(`Hello From Nathdwara ${firstName} ${lastName}`);
myData="Udaipur";
roll=500;
console.log(`${roll} ${myData}`);